stages:
  - build
  - test
  - sonarqube
build:
  stage: build
  script:
    - cd FontysIN
    - ./gradlew build
test:
  stage: test
  script:
    - cd FontysIN
    - ./gradlew test
  dependencies:
    - build

sonarqube:
  stage: sonarqube
  script:
    - cd FontysIN
    - ./gradlew sonarqube
  dependencies:
    - test